### ISSUE TITLE
[ERROR] Thread.sleep InterruptedException:java.nio.channels.OverlappingFileLockException

### ISSUE THREAD

**Issue by NemoAlex** [aliyun/ossimport#5]
在运行时经常会出现这个错误：
```
[2019-01-18 18:44:17]   [ERROR] Thread.sleep InterruptedException:java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
        at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
        at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
        at java.nio.channels.FileChannel.tryLock(Unknown Source)
        at com.aliyun.ossimport.master.scanner.ScannerLock.tryLock(ScannerLock.java:41)
        at com.aliyun.ossimport.master.scanner.ScanExecutor.run(ScanExecutor.java:63)
```

**Comment by guojianfly** [comment]
这个是什么问题？解决了吗？
